[Feature]: Added feature to write serial data using web serial API
Gagan-Space/Cansat-Ground-Station pull request #42
Opened 2024-05-12 10:07 UTC by masterboy376

This PR do the following:
1. Adds `writeData` function toSerial.js file which can be used to write serial data to the connect devices.
2. Modifies `Connect` function to initialize write whenever any new connection is established.
3. Modifies `Disconnect` function to release writer's lock and clear it from the state.

2024-05-12 15:25 UTC, Witty-Wizard requested changes
HI!, @masterboy376 , Can you test if this function works. For that :
1. Go to testing/tester.py
2. In tester.py file add a function that listens for data and prints it.
3. and for sending data send some dummy data for now.
4. once you have made these changes, I will test these changes on actual hardware and if they pass I will merge this PR

2024-05-12 22:25 UTC, Witty-Wizard requested changes

2024-05-12 22:25 UTC, Witty-Wizard commented on src/components/Serial/Serial.js
> +  let receivedData; // Variable for storing received data
Please remove these unused variables.

2024-05-13 07:55 UTC, masterboy376 commented on src/components/Serial/Serial.js
> +  let receivedData; // Variable for storing received data
removed them

2024-05-13 07:56 UTC, masterboy376 commented
> HI!, @masterboy376 , Can you test if this function works. For that :
> 
> 1. Go to testing/tester.py
> 2. In tester.py file add a function that listens for data and prints it.
> 3. and for sending data send some dummy data for now.
> 4. once you have made these changes, I will test these changes on actual hardware and if they pass I will merge this PR

@Witty-Wizard done

2024-05-13 07:56 UTC, masterboy376 commented
@Witty-Wizard  PTAL

2024-05-14 03:01 UTC, Witty-Wizard requested changes

2024-05-14 03:01 UTC, Witty-Wizard commented on testing/tester.py
For testing this on your system there is a tool com0com please try running the script on that, I am getting an error that access is denied. This is an issue related to multiprocessing module and how it handles serial communication.

2024-05-16 08:56 UTC, Witty-Wizard commented on src/components/Serial/Serial.js
> +  while (isConnected && port.writable) {
@masterboy376, please look into this

2024-06-03 07:30 UTC, closed without merging