Added an route for data analysis page
Gagan-Space/Cansat-Ground-Station pull request #70
Opened 2024-05-20 21:31 UTC by AdityaNik

## Related Issue
#33 

## Description
This PR is related to adding an route for data analysis page. A graphical representation of data using an Line Graph.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
<h3>Analysis Page Button</h3>
<img width="959" alt="image" src="https://github.com/Gagan-Space/Cansat-Ground-Station/assets/105343290/674c0491-50ef-4e2c-8664-8a79a42e2450">
<h3>Analysis Page</h3>
<img width="959" alt="image" src="https://github.com/Gagan-Space/Cansat-Ground-Station/assets/105343290/87260f57-7e4e-467f-b3f5-5de64cc8d67a">

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
This is not full implementation of this issue. Happy to receive suggestions and I will work on them....

2024-05-20 21:32 UTC, Witty-Wizard reviewed
Welcome to Our repository.🎊 Thank you so much for taking the time to point this out.

2024-05-21 04:24 UTC, Witty-Wizard requested changes
I have added comments, requesting changes please have a look.

and Good Work!!

2024-05-21 04:24 UTC, Witty-Wizard commented on package.json
>      "d3": "^7.9.0",
You can remove d3, since you are using chart.js d3.js is no longer required

2024-05-21 04:24 UTC, Witty-Wizard commented on src/App.tsx
Shift the main page to a different file and then call it here like you did with Analysis component, this makes the code more readiable

2024-05-21 04:24 UTC, Witty-Wizard commented on src/components/Analysis/UI/Analysis.tsx
In the analysis page, make the graph a separate component, and pass x label, y label, x value, y value, legends to it as a prop. this will allow :
1. To make multiple graphs
2. make code look clean
3. make the code future proof.

2024-05-21 04:24 UTC, Witty-Wizard commented on src/components/Analysis/UI/Analysis.tsx
> +  const handleFileUpload = () => {
Put these functions in a separate file, see the Serial directory for reference, this separates the UI and functional components, making code more readiable

2024-05-21 15:30 UTC, AdityaNik commented on src/components/Analysis/UI/Analysis.tsx
> +  const handleFileUpload = () => {
@Witty-Wizard  This function uses the state variables so can't just seperate them or should i shift them to redux?

2024-05-21 15:57 UTC, Witty-Wizard commented on src/components/Analysis/UI/Analysis.tsx
> +  const handleFileUpload = () => {
U can pass the use state function.

2024-05-21 17:25 UTC, AdityaNik commented
@Witty-Wizard  please review suggested changes...

2024-05-22 04:53 UTC, Witty-Wizard requested changes

2024-05-22 04:53 UTC, Witty-Wizard commented on src/components/Analysis/UI/Analysis.tsx
> +    setChartData({
Can you move all these chart data to plotegraph.tsx, this way when i have to add another graph, I just pass the x and y axis value to it as a prop, you can look at the instrument cluster directory for reference.

2024-05-22 04:53 UTC, Witty-Wizard commented on src/components/Analysis/UI/Analysis.tsx
> +      <Input
Can you change the style of this choose file,
Something like this:
![image](https://github.com/Gagan-Space/Cansat-Ground-Station/assets/48916902/7d75541b-14b8-4ae5-8197-50ed2ddffac1)

2024-05-23 10:21 UTC, Witty-Wizard approved these changes

2024-05-23 10:24 UTC, Witty-Wizard commented
@AdityaNik, Good work I am merging this

2024-05-23 10:24 UTC, merged

2024-05-23 11:53 UTC, AdityaNik commented
had fun working on this one, one of the best mentenor @Witty-Wizard .